### ISSUE TITLE
Incompatible with Sodium 0.4.0 alpha6

### ISSUE THREAD

**Issue by AurelianCaesar** [comp500/Indium#100]
The latest version of Indium 1.0.2 is incompatible with the latest version of Sodium 0.4.0 Alpha6

**Comment by SAJewers** [comment]
Changing the Sodium version dependency in fabric.mod.json does seem to make it work.

**Comment by AurelianCaesar** [comment]
> Changing the Sodium version dependency in fabric.mod.json does seem to make it work.

That only made the game start, I still can't open a world and when I try to join a server the game crashes.

**Comment by SAJewers** [comment]
Disable Colormatic if you have it installed: https://github.com/kvverti/colormatic/issues/74

Disabling Colormatic and changing the version dependency in Indium works for me, I'm able to load into a world.

**Comment by AurelianCaesar** [comment]
> Disable Colormatic if you have it installed: [kvverti/colormatic#74](https://github.com/kvverti/colormatic/issues/74)
> 
> Disabling Colormatic and changing the version dependency in Indium works for me, I'm able to load into a world.

That worked, thank you!

**Comment by kittech0** [comment]
when will be new version of indium on curseforge?

**Comment by ShetiPhian** [comment]
@comp500  Looks to still be in incompatibility with Sodium 0.4.0 alpha6.
A user submitted a crash report (their log: https://pastebin.com/eaLDPCAG)
```
java.lang.NullPointerException: Cannot invoke "java.util.List.isEmpty()" because "quads" is null
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.22)
	at net.minecraft.client.render.item.ItemRenderer.renderBakedItemModel(ItemRenderer:5548)
	at net.minecraft.client.render.item.ItemRenderer.renderItem(ItemRenderer:170)
```

Crash is the same as users who don't have Indium, but this user has it.

'Indium 1.0.2-alpha2+mc1.18.1'
'Sodium 0.4.0-alpha6+build.14'

**Comment by comp500** [comment]
That isn't incompatibility with Sodium; I specify a specific Sodium version in the Indium `fabric.mod.json` for alpha builds so Fabric loader will refuse to even load if the wrong version is used.

It looks like your crash is caused by a broken `BakedModel` which returns `null` from `getQuads`, or a broken `FabricBakedModel` that does so without returning `false` from `isVanillaAdapter` (returning `true` causes Indium to render the model through Sodium's render pipeline, which calls `getQuads` and doesn't like a null list; I'd suggest throwing an exception instead of returning null to indicate when no FRAPI implementation is present).

**Comment by ShetiPhian** [comment]
Its a FabricBakedModel that is returning false from isVanillaAdapter.
Changing that null to a throw likely will save some annoyance, as users will be told to install Indium.

This user must have some other pack error / conflict.
They have the Fabric Rendering API, and Indium, yet the models are still being rendered by Sodium

Edit: Just checked for myself.
Just like the previous build the current build works, so some other mod the user has breaks Indium.
