### ISSUE TITLE
indium 1.0.3 stuck on saving world.

### ISSUE THREAD

**Issue by netcore10** [comp500/Indium#116]
I updated from 1.0.2 to 1.0.3 and now my world loading is stuck 
![image](https://user-images.githubusercontent.com/181536/164998354-731b8825-d51a-4f17-938e-ee71d1705397.png)
works on 1.0.2
[latest.log](https://github.com/comp500/Indium/files/8550577/latest.log)

looks to be null pointer exception.

**Comment by netcore10** [comment]
P.s This is on world creation after 100%

**Comment by KawaiiUzi** [comment]
Having the same issue,  Can't figure out what is causing it.

**Comment by DragonEggBedrockBreaking** [comment]
Update iris to 1.2.3.

**Comment by KawaiiUzi** [comment]
Iris is updated to the latest version for me

**Comment by zndrmn** [comment]
I'm having the same issue here. 
While trying to solve IrisShaders/Iris#1383 
I was able to figure out what was causing the framerate drops but I wasn't able to figure out why Minecraft was still not fully loading into any worlds. I then later found out that indium 1.0.3 was causing the worlds not to load properly. Removing the mod fixed the issue.

My latest.log file
https://gist.github.com/zndrmn/8cd2d8008ced72a6378dd386f4e80e0c#file-latest-log

**Comment by comp500** [comment]
These are most likely different crashes, from different mods. The original poster here is using an outdated version of Iris; if you're still experiencing crashes with the latest version of Iris please make a separate issue with your crash log.

@zndrmn `Mixin apply for mod physicsmod failed physicsmod.mixins.json:vines.MixinIndiumTerrainRenderContext` Your issue is being caused by Physics Mod, see https://github.com/haubna/PhysicsMod/issues/330
