### ISSUE TITLE
Vanilla Tweaks Warm Glow Compatibility

### ISSUE THREAD

**Issue by ghost** [comp500/Indium#164]
Allow Indium to have compatibility with the Vanilla Tweaks Warm Glow texture pack and other lighting capabilities via resource packs.

**Comment by comp500** [comment]
Out of scope for Indium; Indium allows for compatibility with mods using the Fabric Rendering API, not resource packs. The resource pack you mentioned uses core shaders, which are incompatible with Sodium and would be very difficult to make compatible in a generic way (i.e. without rewriting the shaders manually to work with Sodium) due to their low-level nature.

**Comment by ghost** [comment]
I am not too sure with the technical side of the game, especially with Sodium changing the rendering system. I realized a bit later that I made this issue for the wrong mod. I apologize for the mistake. :)
