### ISSUE TITLE
BufferBuilder not started crash (likely to be ImmediatelyFast/owo-lib)

### ISSUE THREAD

**Issue by Lgmrszd** [comp500/Indium#166]
Crash log: https://gist.github.com/Lgmrszd/9b5210aea34a7cadd096ea19b24aaf2c

Versions:
MC: 1.19.2
Quilt Loader: 0.18.1-beta.26
Quilted Fabric API: 4.0.0-beta.25+0.70.0-1.19.2
Sodium: 0.4.4+build.18

**Comment by comp500** [comment]
I can't seem to replicate this crash with EMI 0.5.3+1.19.2 and MI 1.6.2-beta, what versions of EMI and Modern Industrialisation are you using?

**Comment by ChromaPIE** [comment]
Having exactly the same problem with EMI, but I got no MI in my pack. Crash report: https://mclo.gs/tDwTrYE

Follow up: I switched to REI wishing to solve the crashing problem but it happened again. Probably not even related to Indium/REI/EMI so @Lgmrszd if you can provide your mod list I'm able to see what mine and yours have in common.

**Comment by comp500** [comment]
See also: https://github.com/shedaniel/RoughlyEnoughItems/issues/1350 https://github.com/PepperCode1/Continuity/issues/218
From the crash reports in the 3 issues, I found the following mods in common: [common.txt](https://github.com/comp500/Indium/files/10725311/common.txt)
My suspicion is ImmediatelyFast or Satin since those are likely to affect this area of code, but please try to replicate the crash with fewer mods so I can narrow down the culprit (assuming this is an issue in another mod).

**Comment by ChromaPIE** [comment]
ImmediatelyFast is highly suspected. So this kind of issue has been gone for quite a while but returned for the haunting today. Don't know if it's purely out of coincidence, the last two releases of ImmediatelyFast was on Feb 20 and Mar 14, very close to the day the issue was seemingly gone and the return of it. Anyway it's nothing but a dumb guess. Would be appreciated if someone can go to their repo and check the commits for possible clues.

Crash report I got today: https://mclo.gs/RyjNB4b

**Comment by comp500** [comment]
Hmm, from that crash report I noticed that owo lib has a mixin (`io.wispforest.owo.mixin.ui.BufferBuilderMixin (owo.mixins.json)`) that looks like it could cause this behaviour, and this is a mod included in all 3 crash reports. Is it plausible that the crash might have occurred during or after using the interface of Fabric Waystones or Numismatic Overhaul? (both of which use this library)

**Comment by comp500** [comment]
I'm going to guess this is an issue between ImmediatelyFast and owo lib though, not with Indium.

**Comment by RaphiMC** [comment]
I am the developer of ImmediatelyFast. Looking at the mixin of owo lib I can see they are doing pretty whacky stuff to "cancel" rendering of certain buffers which could be the root cause for all the problems (In combination with IF which doesn't expect that behaviour from the BufferBuilder)
Is there a consistent and minimal way to reproduce the issue so I can test around?

**Comment by comp500** [comment]
I haven't seen any consistent way of reproducing the issue - haven't managed to reproduce it at all personally. I think a good starting point would be UIs with items rendered, since this is where the crash stack traces all seem to occur.

**Comment by xamionex** [comment]
I randomly got 2 crashes on this, I hope more logs help I guess
https://mclo.gs/W2tTs8C
https://mclo.gs/LOscfkm

**Comment by comp500** [comment]
Closing: old issue with insufficient information to diagnose
