### ISSUE TITLE
Crash Upon Launch Quilt Claims 'Indium' at Fault

### ISSUE THREAD

**Issue by LadyAirili** [comp500/Indium#188]
All of my mods should be fine as I updated my list to the best of my ability last night, due to a large number of game crashes. However now I can't even get the game to launch, receiving this error message everytime I try: "The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'indium'!" I am not particularly tech savvy so I have no idea what else to try. Here's the full crash report, I hope it helps.
[crash-2023-04-25_14.03.33-client.txt](https://github.com/comp500/Indium/files/11326374/crash-2023-04-25_14.03.33-client.txt)

**Comment by comp500** [comment]
Satin 1.10.0 is incompatible with newer versions of Fabric API/QFAPI, and was only fixed in the 1.11.0 release for 1.19.4. If possible, I suggest updating all your mods to 1.19.4 or removing Satin - it's a library mod that might not be necessary if you don't have a mod that requires it. If you need 1.19.3 and Satin, you can try older versions of QSL/QFAPI.

**Comment by LadyAirili** [comment]
Thank you so much. I don't think I have any mods that actually require satin right now, and my server is in 1.19.3 so I will try that and let you know how it goes. :)

**Comment by LadyAirili** [comment]
It worked for about 45 seconds once I was in my server and then I got this error after a crash: "The game crashed whilst unexpected error
Error: java.nio.BufferUnderflowException"
Do I have to lower my settings? They used to work just fine with no problems, even the heavier biomes like jungle and lush. For about two weeks I've been lucky if I can enter those areas without crashes.
[crash-2023-04-25_22.13.24-client.txt](https://github.com/comp500/Indium/files/11328929/crash-2023-04-25_22.13.24-client.txt)

**Comment by comp500** [comment]
This seems to be an issue between Cull Leaves and Sodium (not sure if it only happens when Iris is installed) though version 3.0.3 claims to have fixed it; see https://github.com/TeamMidnightDust/CullLeaves/pull/36 https://github.com/IrisShaders/Iris/issues/1736 https://github.com/TeamMidnightDust/CullLeaves/issues/37. It might be a good idea to report your crash to the Cull Leaves developers.

**Comment by comp500** [comment]
Closing: not an Indium issue
