### ISSUE TITLE
Indium causes memory leak when switching worlds

### ISSUE THREAD

**Issue by embeddedt** [comp500/Indium#209]
I'm using 1.20 with some other mods, but I think the issue is within Indium (or maybe Sodium). The previous client level can be retained by the thread local in [MixinBlockModelRenderer](https://github.com/comp500/Indium/blob/1.20.x/main/src/main/java/link/infra/indium/mixin/renderer/MixinBlockModelRenderer.java) even if the player changes dimensions. Heap dump screenshot:

![image](https://github.com/comp500/Indium/assets/42941056/20320d7e-1a89-4000-ab43-1468e5b81561)

A simple fix would probably be to store the world using a `WeakReference`, or possibly clear the thread local when the dimension changes.

**Comment by comp500** [comment]
Looks like this was introduced in https://github.com/comp500/Indium/pull/167: when Indium was changed to use the Sodium AO/light caches, a `SingleBlockLightDataCache` was added so that Indium could call a `LightDataAccess` regardless of non-terrain/terrain rendering and always cache AO results. Note that this leak will be cleared up when pistons move blocks, or sand/gravel falls - it won't continually grow.

It also looks like the change to clear `BlockRenderInfo.blockView` in https://github.com/FabricMC/fabric/commit/c154966ed5514e7356c95ceeb4f5c32888cfb0e6 wasn't ported in https://github.com/comp500/Indium/pull/205 - so the thread-local context is holding onto the world here as well. I've fixed that in https://github.com/comp500/Indium/commit/afe94b327599fc18ed8a088099ce5ec239321988 and https://github.com/comp500/Indium/commit/3b66ba1365981400ac63822ac905530da81b80c7.

I'm going to just make the world reference in `SingleBlockLightDataCache` be cleared after every block was rendered. A potential improvement could be to store a render context per-world and clean it up when the world is unloaded, which would also allow using `HashLightDataCache` from Sodium, but this simple fix works for now. (change was discussed in CaffeineMC Discord if more context is desired)
