### ISSUE TITLE
incompatible with sodium 0.5

### ISSUE THREAD

**Issue by Oguzhan5585** [comp500/Indium#219]
game doesn't launch with sodium 0.5 and indium 1.0.21

**Comment by SorkoPiko** [comment]
Same. Please fix as soon as possible!

**Comment by sizquirt** [comment]
@comp500 Please consider looking into this issue as soon as you can.

**Comment by SorkoPiko** [comment]
I think it would be good to make the dependency version a *minimum* not an *exact*.
It would be better if instead of 
```json
"depends": {
	"sodium": "0.4.10"
}
```
`fabric.mod.json` contained
```json
"depends": {
	"sodium": ">=0.4.10"
}
```
All other dependencies use the version as a minimum, so why not sodium? This would allow users to use it in the transition period, and even if it isn't compatible sometimes, it would surely be better that there be an error sometimes over an error occuring always. The minimum dependency can also be changed when the minimum working version changes. Thanks!

**Comment by Valak301** [comment]
I hope they can solve it soon

**Comment by Poopooracoocoo** [comment]
I think it's fine as is. It cuts down on support requests and we already know Indium only works with a certain version of Sodium. It's a friendlier message than a crash report. You can use a Fabric dependency override otherwise.

**Comment by Linxooo** [comment]
I updated iris and it needs to update siduym 0.5, now I can't roll back iris to 1.20.0, overwrote it when I updated, I'm embarrassed now and can only wait for the Indium update

**Comment by 27rogi** [comment]
Stop demanding the mod update, I think Indium developer already knows that Sodium 0.5 is not compatible and requires Indium to be updated. It's a hard work after all and in return there's almost zero profit for them.

@comp500 Good luck with updating this mod, if you will be doing it ❤️

**Comment by 27rogi** [comment]
I also tried to manually change required Sodium version for Indium, but looks like it doesn't go past world loading and instantly crashes.

**Comment by LokeYourC3PH** [comment]
To anyone wanting to post some comment below mine about demanding an update: Sodium made HUGE changes, and Indium will take some time to be updated. I am sure the developer is already aware of it, and will work on it asap.

It is _**NOT**_ necessary for you, yes **_YOU_** to insert any more comments below mine about begging for an update, the dev knows. If I were to make an assumption, it'll take at least a couple of days before an update is released. Until then, keep any Sodium & Indium requiring mods at the versions they're at, and do the same with Sodium & Indium, and only update once Indium is ready as well.

**Comment by comp500** [comment]
Sorry for being asleep 🙃

...yes I do know Sodium 0.5 exists, I already updated to the release candidate on Wednesday - just need to test with the full release.

> I think it would be good to make the dependency version a minimum not an exact.

No, because almost every Sodium update breaks Indium (including this one) so allowing the existing version of Indium to run with Sodium 0.5 would just result in cryptic Mixin crashes ...and even after I update to the new version, I'd still get users forgetting to update Indium and reporting the same crashes, rather than just being told from the start that Indium is incompatible with that version of Sodium.

**Comment by LokeYourC3PH** [comment]
> Sorry for being asleep 🙃
> 
> ...yes I do know Sodium 0.5 exists, I already updated to the release candidate yesterday - just need to test with the full release.
> 
> > I think it would be good to make the dependency version a minimum not an exact.
> 
> No, because almost every Sodium update breaks Indium (including this one) so allowing the existing version of Indium to run with Sodium 0.5 would just result in cryptic Mixin crashes ...and even after I update to the new version, I'd still get users forgetting to update Indium and reporting the same crashes, rather than just being told from the start that Indium is incompatible with that version of Sodium.

Indium is one of the mods where absolutely strict dependency & version compatibility set to an exact is necessary. BDLib is/was overdoing it to an extreme degree, Indium on the other hand I totally understand why it's there, and I also do not think it should be removed at all.

**Comment by vico93** [comment]
> Sorry for being asleep 🙃

I immediately thought about this GIF:
![image](https://media.tenor.com/tw11FMJ8DYAAAAAC/goodnight-sleep.gif)

**Comment by SorkoPiko** [comment]
> Sorry for being asleep 🙃
> 
> ...yes I do know Sodium 0.5 exists, I already updated to the release candidate on Wednesday - just need to test with the full release.
> 
> > I think it would be good to make the dependency version a minimum not an exact.
> 
> No, because almost every Sodium update breaks Indium (including this one) so allowing the existing version of Indium to run with Sodium 0.5 would just result in cryptic Mixin crashes ...and even after I update to the new version, I'd still get users forgetting to update Indium and reporting the same crashes, rather than just being told from the start that Indium is incompatible with that version of Sodium.

Oh, Ok thanks for letting me know. I thought only a small minority of the sodium updates break everything😅
