### ISSUE TITLE
Door and Tall Grass Duplication with Physics Mod and Indium [BUG]

### ISSUE THREAD

**Issue by AqueleHaru** [comp500/Indium#223]
Describe the bug
The doors are duplicated, tall grass are duplicated and the snow is acting weird

![image](https://github.com/comp500/Indium/assets/61639486/8bcfd23e-47d6-446f-b883-4b3f503e2e65)

![image](https://github.com/comp500/Indium/assets/61639486/8d220bb8-85fe-43b4-8ff7-1b31b34c1cc9)

https://github.com/haubna/PhysicsMod/assets/61639486/9e661501-b59f-4797-a611-e260ba069d1f

**Comment by AqueleHaru** [comment]
this started happens only in the last version of indium.

**Comment by comp500** [comment]
Does this occur without Indium but with Sodium?

**Comment by AqueleHaru** [comment]
no. only with indium. with sodium works fine.

**Comment by comp500** [comment]
I'm inclined to believe this is not a problem Indium can fix. Physics Mod is closed-source so it's hard for me to debug what is causing this problem, and it seems to make a lot of invasive patches to other mods - I suggest asking the author of Physics Mod to look into it. Reopen this issue if you know specifically what Indium needs to change in order to be compatible.
