### ISSUE TITLE
Compatability with Sodium not checked in Modrinth

### ISSUE THREAD

**Issue by Davsennn** [comp500/Indium#320]
### Confirmation

- [ ] I have tested the bug without Sodium and Indium.
- [x] I have kept all my mods up to date.

### Bug Description

While using the Modrinth Client: When a version of Sodium is released that Indium is not yet compatible with, it won't show you until you try to launch the game and it says that Indium requires another version of Sodium. This is also annoying when using the "Update All" feature, where Sodium will be updated, even if a compatible version of Sodium was manually installed. Is there a way to list a specific version of Sodium as a dependency so it shows in Modrinth? It would be greatly appreciated.

### Steps to Reproduce

1. Install Sodium and Indium.
2. When a new version of Sodium is released, install it.
3. Indium will not show that it is not compatible with the new version of Sodium.

### Mod Version

any

### Minecraft Version

any

**Comment by comp500** [comment]
I already depend on a specific version of Sodium!
![image](https://github.com/comp500/Indium/assets/1138417/5846ec19-ee84-432d-a003-01f7c513df36)

I can't do much about the Modrinth launcher, you'd have to ask the Modrinth devs to implement that. It might not be ideal even then because I can't specify a dependency on multiple versions of Sodium (e.g. Indium `1.0.34+mc1.20.1` depends on either of `mc1.20.1-0.5.11` or `mc1.20.6-0.5.11`)
